//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragonputer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterSheet
    {
        public long Id { get; set; }
        public long UserProfileId { get; set; }
        public string Sheet { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
